services:
  horizon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: horizon
    ports:
      - "${HORIZON_PORT}:8080"
    volumes:
      - ./config.toml:/app/config.toml
    restart: unless-stopped