version: "3.7"
 
services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mqtt-sdo
    container_name: mqtt-sdo
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

